theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Cornwall Ultimate
description: Information and links for people playing Ultimate Frisbee in Cornwall
